#                        _                                   __      _       __     ___            _        
#  _ __ ___  _   _ _ __ (_)_ __         ___ _ __ ___  _ __  / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| | | | '_ \| | '_ \ _____ / __| '__/ _ \| '_ \| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | | |_| | | | | | | | |_____| (__| | | (_) | | | | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_|      \___|_|  \___/|_| |_| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                           \_\_|        |___/_/                            
- include: install-pkg.yml
- include: make-config.yml
- include: build-local.yml
- include: setup-httpd.yml
